[package]
name = "ugrep"
version = "0.1.0"
authors = ["Anatolijus <anatolijus@gmx.de>"]
edition = "2018"
description = "Command-line tool (clt) searching regular expressions in files."
license = "MIT"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
